### ISSUE TITLE
is this still maintained ?

### ISSUE THREAD

**Issue by ghost** [jgarzik/pynode#20]
cant get it to work., many dependencies are no more available., and throws errors. 

[root@localhost pynode]# ./node.py pynode.conf
Traceback (most recent call last):
  File "./node.py", line 27, in <module>
    import rpc
  File "/home/deploy/pynode/rpc.py", line 20, in <module>
    import ChainDb
  File "/home/deploy/pynode/ChainDb.py", line 18, in <module>
    from bitcoin.serialize import *
ImportError: No module named serialize

**Comment by Fl0x23** [comment]
I get the same error. Any help?
